services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: error-free-db
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
